# Generated by Django 3.2 on 2023-04-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to='static/MainPage/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/MainPage/img'),
        ),
    ]
