# Generated by Django 3.2 on 2023-05-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0005_auto_20230428_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('MainPage.page',),
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('cat1', 'Category 1'), ('cat2', 'Category 2'), ('cat3', 'Category 3'), ('cat4', 'Category 4'), ('cat5', 'Category 5'), ('cat6', 'Category 6'), ('cat7', 'Category 7'), ('cat8', 'Category 8'), ('cat9', 'Category 9')], default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/MainPage/img'),
        ),
    ]
