# Generated by Django 3.2 on 2023-05-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0009_auto_20230502_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPage',
        ),
    ]
